//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 10:22:09 AM ICT 
//


package vn.nsw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reference">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="From">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="To">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Subject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="function" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="preReference" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="documentYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="sendDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reference",
    "from",
    "to",
    "subject"
})
@XmlRootElement(name = "Header")
public class Header {

    @XmlElement(name = "Reference", required = true)
    protected Header.Reference reference;
    @XmlElement(name = "From", required = true)
    protected Header.From from;
    @XmlElement(name = "To", required = true)
    protected Header.To to;
    @XmlElement(name = "Subject", required = true)
    protected Header.Subject subject;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Header.Reference }
     *     
     */
    public Header.Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header.Reference }
     *     
     */
    public void setReference(Header.Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link Header.From }
     *     
     */
    public Header.From getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header.From }
     *     
     */
    public void setFrom(Header.From value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link Header.To }
     *     
     */
    public Header.To getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header.To }
     *     
     */
    public void setTo(Header.To value) {
        this.to = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link Header.Subject }
     *     
     */
    public Header.Subject getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header.Subject }
     *     
     */
    public void setSubject(Header.Subject value) {
        this.subject = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "identity",
        "countryCode",
        "ministryCode",
        "organizationCode",
        "unitCode"
    })
    public static class From {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String identity;
        @XmlElement(required = false)
        protected String countryCode;
        @XmlElement(required = false)
        protected String ministryCode;
        @XmlElement(required = false)
        protected String organizationCode;
        @XmlElement(required = false)
        protected String unitCode;
        
        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the identity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentity() {
            return identity;
        }

        /**
         * Sets the value of the identity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentity(String value) {
            this.identity = value;
        }

		public String getCountryCode() {
			return countryCode;
		}

		public void setCountryCode(String countryCode) {
			this.countryCode = countryCode;
		}

		public String getMinistryCode() {
			return ministryCode;
		}

		public void setMinistryCode(String ministryCode) {
			this.ministryCode = ministryCode;
		}

		public String getOrganizationCode() {
			return organizationCode;
		}

		public void setOrganizationCode(String organizationCode) {
			this.organizationCode = organizationCode;
		}

		public String getUnitCode() {
			return unitCode;
		}

		public void setUnitCode(String unitCode) {
			this.unitCode = unitCode;
		}

        
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "messageId"
    })
    public static class Reference {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(required = true)
        protected String messageId;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the messageId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageId() {
            return messageId;
        }

        /**
         * Sets the value of the messageId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageId(String value) {
            this.messageId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="function" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="preReference" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="documentYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="sendDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentType",
        "type",
        "function",
        "reference",
        "preReference",
        "documentYear",
        "sendDate"
    })
    public static class Subject {

        protected int documentType;
        protected int type;
        protected String function;
        protected long reference;
        protected long preReference;
        protected int documentYear;
        @XmlElement(required = true)
        protected String sendDate;

        /**
         * Gets the value of the documentType property.
         * 
         */
        public int getDocumentType() {
            return documentType;
        }

        /**
         * Sets the value of the documentType property.
         * 
         */
        public void setDocumentType(int value) {
            this.documentType = value;
        }

        /**
         * Gets the value of the type property.
         * 
         */
        public int getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         */
        public void setType(int value) {
            this.type = value;
        }

        /**
         * Gets the value of the function property.
         * 
         */
        public String getFunction() {
            return function;
        }

        /**
         * Sets the value of the function property.
         * 
         */
        public void setFunction(String value) {
            this.function = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         */
        public long getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         */
        public void setReference(long value) {
            this.reference = value;
        }

        /**
         * Gets the value of the preReference property.
         * 
         */
        public long getPreReference() {
            return preReference;
        }

        /**
         * Sets the value of the preReference property.
         * 
         */
        public void setPreReference(long value) {
            this.preReference = value;
        }

        /**
         * Gets the value of the documentYear property.
         * 
         */
        public int getDocumentYear() {
            return documentYear;
        }

        /**
         * Sets the value of the documentYear property.
         * 
         */
        public void setDocumentYear(int value) {
            this.documentYear = value;
        }

        /**
         * Gets the value of the sendDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSendDate() {
            return sendDate;
        }

        /**
         * Sets the value of the sendDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSendDate(String value) {
            this.sendDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "identity",
        "countryCode",  
        "ministryCode",
        "organizationCode",
        "unitCode"        
    })
    public static class To {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String identity;
        @XmlElement(required = false)
        protected String countryCode;
        @XmlElement(required = false)
        protected String ministryCode;
        @XmlElement(required = false)
        protected String organizationCode;
        @XmlElement(required = false)
        protected String unitCode;
        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the identity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentity() {
            return identity;
        }

        /**
         * Sets the value of the identity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentity(String value) {
            this.identity = value;
        }

		public String getCountryCode() {
			return countryCode;
		}

		public void setCountryCode(String countryCode) {
			this.countryCode = countryCode;
		}

		public String getMinistryCode() {
			return ministryCode;
		}

		public void setMinistryCode(String ministryCode) {
			this.ministryCode = ministryCode;
		}

		public String getOrganizationCode() {
			return organizationCode;
		}

		public void setOrganizationCode(String organizationCode) {
			this.organizationCode = organizationCode;
		}

		public String getUnitCode() {
			return unitCode;
		}

		public void setUnitCode(String unitCode) {
			this.unitCode = unitCode;
		}

    }

}
