//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.29 at 02:56:26 PM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DmDataitem" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataGroupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Code0" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Node1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Node2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Node3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Node4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ValidatedFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ValidatedTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dmDataItem"
})
@XmlRootElement(name = "DmDataItemList")
public class DmDataItemList {

    @XmlElement(name = "DmDataitem", required = true)
    protected List<DmDataItemList.DmDataitem> dmDataItem;

    /**
     * Gets the value of the dmDataItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dmDataItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDmDataItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmDataItemList.DmDataitem }
     * 
     * 
     */
    public List<DmDataItemList.DmDataitem> getDmDataItem() {
        if (dmDataItem == null) {
            dmDataItem = new ArrayList<DmDataItemList.DmDataitem>();
        }
        return this.dmDataItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataGroupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Code0" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Node1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Node2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Node3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Node4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ValidatedFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ValidatedTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataGroupId",
        "code0",
        "node1",
        "node2",
        "node3",
        "node4",
        "level",
        "name",
        "shortName",
        "description",
        "validatedFrom",
        "validatedTo",
        "order",
        "status"
    })
    public static class DmDataitem {

        @XmlElement(name = "DataGroupId", required = true)
        protected String dataGroupId;
        @XmlElement(name = "Code0", required = true)
        protected String code0;
        @XmlElement(name = "Node1", required = true)
        protected String node1;
        @XmlElement(name = "Node2", required = true)
        protected String node2;
        @XmlElement(name = "Node3", required = true)
        protected String node3;
        @XmlElement(name = "Node4", required = true)
        protected String node4;
        @XmlElement(name = "Level")
        protected int level;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "ShortName", required = true)
        protected String shortName;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "ValidatedFrom", required = true)
        protected String validatedFrom;
        @XmlElement(name = "ValidatedTo", required = true)
        protected String validatedTo;
        @XmlElement(name = "Order")
        protected int order;
        @XmlElement(name = "Status")
        protected int status;

        /**
         * Gets the value of the dataGroupId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataGroupId() {
            return dataGroupId;
        }

        /**
         * Sets the value of the dataGroupId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataGroupId(String value) {
            this.dataGroupId = value;
        }

        /**
         * Gets the value of the code0 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode0() {
            return code0;
        }

        /**
         * Sets the value of the code0 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode0(String value) {
            this.code0 = value;
        }

        /**
         * Gets the value of the node1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNode1() {
            return node1;
        }

        /**
         * Sets the value of the node1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNode1(String value) {
            this.node1 = value;
        }

        /**
         * Gets the value of the node2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNode2() {
            return node2;
        }

        /**
         * Sets the value of the node2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNode2(String value) {
            this.node2 = value;
        }

        /**
         * Gets the value of the node3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNode3() {
            return node3;
        }

        /**
         * Sets the value of the node3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNode3(String value) {
            this.node3 = value;
        }

        /**
         * Gets the value of the node4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNode4() {
            return node4;
        }

        /**
         * Sets the value of the node4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNode4(String value) {
            this.node4 = value;
        }

        /**
         * Gets the value of the level property.
         * 
         */
        public int getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         * 
         */
        public void setLevel(int value) {
            this.level = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the shortName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortName() {
            return shortName;
        }

        /**
         * Sets the value of the shortName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortName(String value) {
            this.shortName = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the validatedFrom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidatedFrom() {
            return validatedFrom;
        }

        /**
         * Sets the value of the validatedFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidatedFrom(String value) {
            this.validatedFrom = value;
        }

        /**
         * Gets the value of the validatedTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidatedTo() {
            return validatedTo;
        }

        /**
         * Sets the value of the validatedTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidatedTo(String value) {
            this.validatedTo = value;
        }

        /**
         * Gets the value of the order property.
         * 
         */
        public int getOrder() {
            return order;
        }

        /**
         * Sets the value of the order property.
         * 
         */
        public void setOrder(int value) {
            this.order = value;
        }

        /**
         * Gets the value of the status property.
         * 
         */
        public int getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         */
        public void setStatus(int value) {
            this.status = value;
        }

    }

}
