//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.22 at 10:10:15 AM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DmHistoryShipOwner" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MaritimeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShipOwnerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TaxCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CompanyAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TelNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FaxNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CompanyShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsShipOwner" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="IsShipOperator" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="IsOther" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SyncVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dmHistoryShipOwner"
})
@XmlRootElement(name = "DmHistoryShipOwnerList")
public class DmHistoryShipOwnerList {

    @XmlElement(name = "DmHistoryShipOwner", required = true)
    protected List<DmHistoryShipOwnerList.DmHistoryShipOwner> dmHistoryShipOwner;

    /**
     * Gets the value of the dmHistoryShipOwner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dmHistoryShipOwner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDmHistoryShipOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmHistoryShipOwnerList.DmHistoryShipOwner }
     * 
     * 
     */
    public List<DmHistoryShipOwnerList.DmHistoryShipOwner> getDmHistoryShipOwner() {
        if (dmHistoryShipOwner == null) {
            dmHistoryShipOwner = new ArrayList<DmHistoryShipOwnerList.DmHistoryShipOwner>();
        }
        return this.dmHistoryShipOwner;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MaritimeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShipOwnerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TaxCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CompanyAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TelNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FaxNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CompanyShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsShipOwner" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="IsShipOperator" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="IsOther" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SyncVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "maritimeCode",
        "shipOwnerCode",
        "taxCode",
        "companyName",
        "companyAddress",
        "contactEmail",
        "telNo",
        "faxNo",
        "companyShortName",
        "isShipOwner",
        "isShipOperator",
        "isOther",
        "remarks",
        "status",
        "syncVersion"
    })
    public static class DmHistoryShipOwner {

        @XmlElement(name = "MaritimeCode", required = true)
        protected String maritimeCode;
        @XmlElement(name = "ShipOwnerCode", required = true)
        protected String shipOwnerCode;
        @XmlElement(name = "TaxCode", required = true)
        protected String taxCode;
        @XmlElement(name = "CompanyName", required = true)
        protected String companyName;
        @XmlElement(name = "CompanyAddress", required = true)
        protected String companyAddress;
        @XmlElement(name = "ContactEmail", required = true)
        protected String contactEmail;
        @XmlElement(name = "TelNo", required = true)
        protected String telNo;
        @XmlElement(name = "FaxNo", required = true)
        protected String faxNo;
        @XmlElement(name = "CompanyShortName", required = true)
        protected String companyShortName;
        @XmlElement(name = "IsShipOwner")
        protected int isShipOwner;
        @XmlElement(name = "IsShipOperator")
        protected int isShipOperator;
        @XmlElement(name = "IsOther")
        protected int isOther;
        @XmlElement(name = "Remarks", required = true)
        protected String remarks;
        @XmlElement(name = "Status")
        protected int status;
        @XmlElement(name = "SyncVersion", required = true)
        protected String syncVersion;

        /**
         * Gets the value of the maritimeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeCode() {
            return maritimeCode;
        }

        /**
         * Sets the value of the maritimeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeCode(String value) {
            this.maritimeCode = value;
        }

        /**
         * Gets the value of the shipOwnerCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipOwnerCode() {
            return shipOwnerCode;
        }

        /**
         * Sets the value of the shipOwnerCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipOwnerCode(String value) {
            this.shipOwnerCode = value;
        }

        /**
         * Gets the value of the taxCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxCode() {
            return taxCode;
        }

        /**
         * Sets the value of the taxCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxCode(String value) {
            this.taxCode = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyName(String value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the companyAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyAddress() {
            return companyAddress;
        }

        /**
         * Sets the value of the companyAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyAddress(String value) {
            this.companyAddress = value;
        }

        /**
         * Gets the value of the contactEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactEmail() {
            return contactEmail;
        }

        /**
         * Sets the value of the contactEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactEmail(String value) {
            this.contactEmail = value;
        }

        /**
         * Gets the value of the telNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelNo() {
            return telNo;
        }

        /**
         * Sets the value of the telNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelNo(String value) {
            this.telNo = value;
        }

        /**
         * Gets the value of the faxNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFaxNo() {
            return faxNo;
        }

        /**
         * Sets the value of the faxNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFaxNo(String value) {
            this.faxNo = value;
        }

        /**
         * Gets the value of the companyShortName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyShortName() {
            return companyShortName;
        }

        /**
         * Sets the value of the companyShortName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyShortName(String value) {
            this.companyShortName = value;
        }

        /**
         * Gets the value of the isShipOwner property.
         * 
         */
        public int getIsShipOwner() {
            return isShipOwner;
        }

        /**
         * Sets the value of the isShipOwner property.
         * 
         */
        public void setIsShipOwner(int value) {
            this.isShipOwner = value;
        }

        /**
         * Gets the value of the isShipOperator property.
         * 
         */
        public int getIsShipOperator() {
            return isShipOperator;
        }

        /**
         * Sets the value of the isShipOperator property.
         * 
         */
        public void setIsShipOperator(int value) {
            this.isShipOperator = value;
        }

        /**
         * Gets the value of the isOther property.
         * 
         */
        public int getIsOther() {
            return isOther;
        }

        /**
         * Sets the value of the isOther property.
         * 
         */
        public void setIsOther(int value) {
            this.isOther = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

        /**
         * Gets the value of the status property.
         * 
         */
        public int getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         */
        public void setStatus(int value) {
            this.status = value;
        }

        /**
         * Gets the value of the syncVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSyncVersion() {
            return syncVersion;
        }

        /**
         * Sets the value of the syncVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSyncVersion(String value) {
            this.syncVersion = value;
        }

    }

}
