//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.29 at 03:51:55 PM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DmHistoryMaritime" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MaritimeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MaritimeReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MaritimeOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MaritimeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MaritimeNameVN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AddressVN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CityCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsDelete" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MarkedAsDelete" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RequestedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SyncVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dmHistoryMaritime"
})
@XmlRootElement(name = "DmHistoryMaritimeList")
public class DmHistoryMaritimeList {

    @XmlElement(name = "DmHistoryMaritime", required = true)
    protected List<DmHistoryMaritimeList.DmHistoryMaritime> dmHistoryMaritime;

    /**
     * Gets the value of the dmHistoryMaritime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dmHistoryMaritime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDmHistoryMaritime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmHistoryMaritimeList.DmHistoryMaritime }
     * 
     * 
     */
    public List<DmHistoryMaritimeList.DmHistoryMaritime> getDmHistoryMaritime() {
        if (dmHistoryMaritime == null) {
            dmHistoryMaritime = new ArrayList<DmHistoryMaritimeList.DmHistoryMaritime>();
        }
        return this.dmHistoryMaritime;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MaritimeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MaritimeReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MaritimeOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MaritimeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MaritimeNameVN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AddressVN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CityCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsDelete" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MarkedAsDelete" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RequestedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SyncVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "maritimeCode",
        "maritimeReference",
        "maritimeOrder",
        "maritimeName",
        "maritimeNameVN",
        "address",
        "addressVN",
        "stateCode",
        "cityCode",
        "isDelete",
        "markedAsDelete",
        "modifiedDate",
        "requestedDate",
        "syncVersion"
    })
    public static class DmHistoryMaritime {

        @XmlElement(name = "MaritimeCode", required = true)
        protected String maritimeCode;
        @XmlElement(name = "MaritimeReference", required = true)
        protected String maritimeReference;
        @XmlElement(name = "MaritimeOrder", required = true)
        protected String maritimeOrder;
        @XmlElement(name = "MaritimeName", required = true)
        protected String maritimeName;
        @XmlElement(name = "MaritimeNameVN", required = true)
        protected String maritimeNameVN;
        @XmlElement(name = "Address", required = true)
        protected String address;
        @XmlElement(name = "AddressVN", required = true)
        protected String addressVN;
        @XmlElement(name = "StateCode", required = true)
        protected String stateCode;
        @XmlElement(name = "CityCode", required = true)
        protected String cityCode;
        @XmlElement(name = "IsDelete", required = true)
        protected String isDelete;
        @XmlElement(name = "MarkedAsDelete", required = true)
        protected String markedAsDelete;
        @XmlElement(name = "ModifiedDate", required = true)
        protected String modifiedDate;
        @XmlElement(name = "RequestedDate", required = true)
        protected String requestedDate;
        @XmlElement(name = "SyncVersion", required = true)
        protected String syncVersion;

        /**
         * Gets the value of the maritimeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeCode() {
            return maritimeCode;
        }

        /**
         * Sets the value of the maritimeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeCode(String value) {
            this.maritimeCode = value;
        }

        /**
         * Gets the value of the maritimeReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeReference() {
            return maritimeReference;
        }

        /**
         * Sets the value of the maritimeReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeReference(String value) {
            this.maritimeReference = value;
        }

        /**
         * Gets the value of the maritimeOrder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeOrder() {
            return maritimeOrder;
        }

        /**
         * Sets the value of the maritimeOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeOrder(String value) {
            this.maritimeOrder = value;
        }

        /**
         * Gets the value of the maritimeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeName() {
            return maritimeName;
        }

        /**
         * Sets the value of the maritimeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeName(String value) {
            this.maritimeName = value;
        }

        /**
         * Gets the value of the maritimeNameVN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeNameVN() {
            return maritimeNameVN;
        }

        /**
         * Sets the value of the maritimeNameVN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeNameVN(String value) {
            this.maritimeNameVN = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the addressVN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressVN() {
            return addressVN;
        }

        /**
         * Sets the value of the addressVN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressVN(String value) {
            this.addressVN = value;
        }

        /**
         * Gets the value of the stateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStateCode() {
            return stateCode;
        }

        /**
         * Sets the value of the stateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStateCode(String value) {
            this.stateCode = value;
        }

        /**
         * Gets the value of the cityCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCityCode() {
            return cityCode;
        }

        /**
         * Sets the value of the cityCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCityCode(String value) {
            this.cityCode = value;
        }

        /**
         * Gets the value of the isDelete property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsDelete() {
            return isDelete;
        }

        /**
         * Sets the value of the isDelete property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsDelete(String value) {
            this.isDelete = value;
        }

        /**
         * Gets the value of the markedAsDelete property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMarkedAsDelete() {
            return markedAsDelete;
        }

        /**
         * Sets the value of the markedAsDelete property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMarkedAsDelete(String value) {
            this.markedAsDelete = value;
        }

        /**
         * Gets the value of the modifiedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModifiedDate() {
            return modifiedDate;
        }

        /**
         * Sets the value of the modifiedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModifiedDate(String value) {
            this.modifiedDate = value;
        }

        /**
         * Gets the value of the requestedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestedDate() {
            return requestedDate;
        }

        /**
         * Sets the value of the requestedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestedDate(String value) {
            this.requestedDate = value;
        }

        /**
         * Gets the value of the syncVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSyncVersion() {
            return syncVersion;
        }

        /**
         * Sets the value of the syncVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSyncVersion(String value) {
            this.syncVersion = value;
        }

    }

}
