//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.31 at 04:26:39 PM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DmVmaPilot" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MaritimeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotBOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotCertificateNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotCertificateDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PilotExpiredDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SyncVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dmVmaPilot"
})
@XmlRootElement(name = "DmVmaPilotList")
public class DmVmaPilotList {

    @XmlElement(name = "DmVmaPilot", required = true)
    protected List<DmVmaPilotList.DmVmaPilot> dmVmaPilot;

    /**
     * Gets the value of the dmVmaPilot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dmVmaPilot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDmVmaPilot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmVmaPilotList.DmVmaPilot }
     * 
     * 
     */
    public List<DmVmaPilotList.DmVmaPilot> getDmVmaPilot() {
        if (dmVmaPilot == null) {
            dmVmaPilot = new ArrayList<DmVmaPilotList.DmVmaPilot>();
        }
        return this.dmVmaPilot;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MaritimeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotBOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotCertificateNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotCertificateDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PilotExpiredDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SyncVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "maritimeCode",
        "pilotCompanyCode",
        "pilotCompanyName",
        "pilotCode",
        "pilotName",
        "pilotBOD",
        "pilotNo",
        "pilotCertificateNo",
        "pilotCertificateDate",
        "pilotCategoryCode",
        "remarks",
        "pilotShortName",
        "pilotExpiredDate",
        "status",
        "syncVersion"
    })
    public static class DmVmaPilot {

        @XmlElement(name = "MaritimeCode", required = true)
        protected String maritimeCode;
        @XmlElement(name = "PilotCompanyCode", required = true)
        protected String pilotCompanyCode;
        @XmlElement(name = "PilotCompanyName", required = true)
        protected String pilotCompanyName;
        @XmlElement(name = "PilotCode", required = true)
        protected String pilotCode;
        @XmlElement(name = "PilotName", required = true)
        protected String pilotName;
        @XmlElement(name = "PilotBOD", required = true)
        protected String pilotBOD;
        @XmlElement(name = "PilotNo", required = true)
        protected String pilotNo;
        @XmlElement(name = "PilotCertificateNo", required = true)
        protected String pilotCertificateNo;
        @XmlElement(name = "PilotCertificateDate", required = true)
        protected String pilotCertificateDate;
        @XmlElement(name = "PilotCategoryCode", required = true)
        protected String pilotCategoryCode;
        @XmlElement(name = "Remarks", required = true)
        protected String remarks;
        @XmlElement(name = "PilotShortName", required = true)
        protected String pilotShortName;
        @XmlElement(name = "PilotExpiredDate", required = true)
        protected String pilotExpiredDate;
        @XmlElement(name = "Status")
        protected int status;
        @XmlElement(name = "SyncVersion", required = true)
        protected String syncVersion;

        /**
         * Gets the value of the maritimeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritimeCode() {
            return maritimeCode;
        }

        /**
         * Sets the value of the maritimeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritimeCode(String value) {
            this.maritimeCode = value;
        }

        /**
         * Gets the value of the pilotCompanyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotCompanyCode() {
            return pilotCompanyCode;
        }

        /**
         * Sets the value of the pilotCompanyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotCompanyCode(String value) {
            this.pilotCompanyCode = value;
        }

        /**
         * Gets the value of the pilotCompanyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotCompanyName() {
            return pilotCompanyName;
        }

        /**
         * Sets the value of the pilotCompanyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotCompanyName(String value) {
            this.pilotCompanyName = value;
        }

        /**
         * Gets the value of the pilotCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotCode() {
            return pilotCode;
        }

        /**
         * Sets the value of the pilotCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotCode(String value) {
            this.pilotCode = value;
        }

        /**
         * Gets the value of the pilotName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotName() {
            return pilotName;
        }

        /**
         * Sets the value of the pilotName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotName(String value) {
            this.pilotName = value;
        }

        /**
         * Gets the value of the pilotBOD property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotBOD() {
            return pilotBOD;
        }

        /**
         * Sets the value of the pilotBOD property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotBOD(String value) {
            this.pilotBOD = value;
        }

        /**
         * Gets the value of the pilotNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotNo() {
            return pilotNo;
        }

        /**
         * Sets the value of the pilotNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotNo(String value) {
            this.pilotNo = value;
        }

        /**
         * Gets the value of the pilotCertificateNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotCertificateNo() {
            return pilotCertificateNo;
        }

        /**
         * Sets the value of the pilotCertificateNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotCertificateNo(String value) {
            this.pilotCertificateNo = value;
        }

        /**
         * Gets the value of the pilotCertificateDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotCertificateDate() {
            return pilotCertificateDate;
        }

        /**
         * Sets the value of the pilotCertificateDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotCertificateDate(String value) {
            this.pilotCertificateDate = value;
        }

        /**
         * Gets the value of the pilotCategoryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotCategoryCode() {
            return pilotCategoryCode;
        }

        /**
         * Sets the value of the pilotCategoryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotCategoryCode(String value) {
            this.pilotCategoryCode = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

        /**
         * Gets the value of the pilotShortName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotShortName() {
            return pilotShortName;
        }

        /**
         * Sets the value of the pilotShortName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotShortName(String value) {
            this.pilotShortName = value;
        }

        /**
         * Gets the value of the pilotExpiredDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPilotExpiredDate() {
            return pilotExpiredDate;
        }

        /**
         * Sets the value of the pilotExpiredDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPilotExpiredDate(String value) {
            this.pilotExpiredDate = value;
        }

        /**
         * Gets the value of the status property.
         * 
         */
        public int getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         */
        public void setStatus(int value) {
            this.status = value;
        }

        /**
         * Gets the value of the syncVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSyncVersion() {
            return syncVersion;
        }

        /**
         * Sets the value of the syncVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSyncVersion(String value) {
            this.syncVersion = value;
        }

    }

}
