//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 10:39:12 AM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeclarationOfHealth" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DocumentYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SubmittedPortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DateSubmitted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NameOfShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Registration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IMONumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ArrivingFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SailingTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MasterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GrossTonnage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GrossTonnageUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Tonnage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TonnageUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CertificateCarried" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IssuedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ReInspectionRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsShipVisitedWHO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="VisitedWHOPortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DateOfVisitedWHO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ListPortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DoctorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DoctorSignDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HealthCrewPassengerList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HealthCrewPassenger" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="HealthCrewPassengerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PassengerOrCrewCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PassengerOrCrewName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ClassOrRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="StateVisitedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PortVisitedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ToDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HealthQuestion" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HealthQuestionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PersonDied" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PersonDiedNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PersonDiedReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsInfectious" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InfectiousReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IllPassengersGreaterNomal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IllPassengersNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IllPersonsOnBoard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IllPersonsReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MedicalPractitionerConsulted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MedicalTreatmentOrAdvice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InfectionOrSpreadOfDisease" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InfectionsReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsSanitary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SanitaryDes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsStowaways" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JoinShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsAnimal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AttachmentDeclarationHealth">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Attachment" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AttachmentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PassengerOrCrewCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PortJoinVesselCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DateJoinVessel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ClassOrRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NatureOfIllness" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DateOfOnsetOfSymptom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ReportedMedicalOfficer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DisposalOfCase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MedicinesOrOther" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SignPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MasterSigned" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "declarationOfHealth",
    "healthCrewPassengerList",
    "healthQuestion",
    "attachmentDeclarationHealth",
    "signPlace",
    "signDate",
    "masterSigned"
})
@XmlRootElement(name = "HealthQuanrantineDeclare")
public class HealthQuanrantineDeclare {

    @XmlElement(name = "DeclarationOfHealth", required = true)
    protected List<HealthQuanrantineDeclare.DeclarationOfHealth> declarationOfHealth;
    @XmlElement(name = "HealthCrewPassengerList", required = true)
    protected HealthQuanrantineDeclare.HealthCrewPassengerList healthCrewPassengerList;
    @XmlElement(name = "HealthQuestion", required = true)
    protected List<HealthQuanrantineDeclare.HealthQuestion> healthQuestion;
    @XmlElement(name = "AttachmentDeclarationHealth", required = true)
    protected HealthQuanrantineDeclare.AttachmentDeclarationHealth attachmentDeclarationHealth;
    @XmlElement(name = "SignPlace", required = true)
    protected String signPlace;
    @XmlElement(name = "SignDate", required = true)
    protected String signDate;
    @XmlElement(name = "MasterSigned", required = true)
    protected String masterSigned;

    /**
     * Gets the value of the declarationOfHealth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the declarationOfHealth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeclarationOfHealth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HealthQuanrantineDeclare.DeclarationOfHealth }
     * 
     * 
     */
    public List<HealthQuanrantineDeclare.DeclarationOfHealth> getDeclarationOfHealth() {
        if (declarationOfHealth == null) {
            declarationOfHealth = new ArrayList<HealthQuanrantineDeclare.DeclarationOfHealth>();
        }
        return this.declarationOfHealth;
    }

    /**
     * Gets the value of the healthCrewPassengerList property.
     * 
     * @return
     *     possible object is
     *     {@link HealthQuanrantineDeclare.HealthCrewPassengerList }
     *     
     */
    public HealthQuanrantineDeclare.HealthCrewPassengerList getHealthCrewPassengerList() {
        return healthCrewPassengerList;
    }

    /**
     * Sets the value of the healthCrewPassengerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthQuanrantineDeclare.HealthCrewPassengerList }
     *     
     */
    public void setHealthCrewPassengerList(HealthQuanrantineDeclare.HealthCrewPassengerList value) {
        this.healthCrewPassengerList = value;
    }

    /**
     * Gets the value of the healthQuestion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the healthQuestion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHealthQuestion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HealthQuanrantineDeclare.HealthQuestion }
     * 
     * 
     */
    public List<HealthQuanrantineDeclare.HealthQuestion> getHealthQuestion() {
        if (healthQuestion == null) {
            healthQuestion = new ArrayList<HealthQuanrantineDeclare.HealthQuestion>();
        }
        return this.healthQuestion;
    }

    /**
     * Gets the value of the attachmentDeclarationHealth property.
     * 
     * @return
     *     possible object is
     *     {@link HealthQuanrantineDeclare.AttachmentDeclarationHealth }
     *     
     */
    public HealthQuanrantineDeclare.AttachmentDeclarationHealth getAttachmentDeclarationHealth() {
        return attachmentDeclarationHealth;
    }

    /**
     * Sets the value of the attachmentDeclarationHealth property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthQuanrantineDeclare.AttachmentDeclarationHealth }
     *     
     */
    public void setAttachmentDeclarationHealth(HealthQuanrantineDeclare.AttachmentDeclarationHealth value) {
        this.attachmentDeclarationHealth = value;
    }

    /**
     * Gets the value of the signPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignPlace() {
        return signPlace;
    }

    /**
     * Sets the value of the signPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignPlace(String value) {
        this.signPlace = value;
    }

    /**
     * Gets the value of the signDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * Sets the value of the signDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignDate(String value) {
        this.signDate = value;
    }

    /**
     * Gets the value of the masterSigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterSigned() {
        return masterSigned;
    }

    /**
     * Sets the value of the masterSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterSigned(String value) {
        this.masterSigned = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Attachment" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AttachmentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PassengerOrCrewCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PortJoinVesselCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DateJoinVessel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ClassOrRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NatureOfIllness" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DateOfOnsetOfSymptom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ReportedMedicalOfficer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DisposalOfCase" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MedicinesOrOther" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attachment"
    })
    public static class AttachmentDeclarationHealth {

        @XmlElement(name = "Attachment", required = true)
        protected List<HealthQuanrantineDeclare.AttachmentDeclarationHealth.Attachment> attachment;

        /**
         * Gets the value of the attachment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attachment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttachment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HealthQuanrantineDeclare.AttachmentDeclarationHealth.Attachment }
         * 
         * 
         */
        public List<HealthQuanrantineDeclare.AttachmentDeclarationHealth.Attachment> getAttachment() {
            if (attachment == null) {
                attachment = new ArrayList<HealthQuanrantineDeclare.AttachmentDeclarationHealth.Attachment>();
            }
            return this.attachment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AttachmentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PassengerOrCrewCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PortJoinVesselCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DateJoinVessel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ClassOrRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NatureOfIllness" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DateOfOnsetOfSymptom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ReportedMedicalOfficer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DisposalOfCase" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MedicinesOrOther" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attachmentCode",
            "passengerOrCrewCode",
            "name",
            "age",
            "sex",
            "nationality",
            "portJoinVesselCode",
            "dateJoinVessel",
            "classOrRating",
            "natureOfIllness",
            "dateOfOnsetOfSymptom",
            "reportedMedicalOfficer",
            "disposalOfCase",
            "medicinesOrOther",
            "comments"
        })
        public static class Attachment {

            @XmlElement(name = "AttachmentCode", required = true)
            protected String attachmentCode;
            @XmlElement(name = "PassengerOrCrewCode", required = true)
            protected String passengerOrCrewCode;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Age", required = true)
            protected String age;
            @XmlElement(name = "Sex", required = true)
            protected String sex;
            @XmlElement(name = "Nationality", required = true)
            protected String nationality;
            @XmlElement(name = "PortJoinVesselCode", required = true)
            protected String portJoinVesselCode;
            @XmlElement(name = "DateJoinVessel", required = true)
            protected String dateJoinVessel;
            @XmlElement(name = "ClassOrRating", required = true)
            protected String classOrRating;
            @XmlElement(name = "NatureOfIllness", required = true)
            protected String natureOfIllness;
            @XmlElement(name = "DateOfOnsetOfSymptom", required = true)
            protected String dateOfOnsetOfSymptom;
            @XmlElement(name = "ReportedMedicalOfficer", required = true)
            protected String reportedMedicalOfficer;
            @XmlElement(name = "DisposalOfCase", required = true)
            protected String disposalOfCase;
            @XmlElement(name = "MedicinesOrOther", required = true)
            protected String medicinesOrOther;
            @XmlElement(name = "Comments", required = true)
            protected String comments;

            /**
             * Gets the value of the attachmentCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttachmentCode() {
                return attachmentCode;
            }

            /**
             * Sets the value of the attachmentCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttachmentCode(String value) {
                this.attachmentCode = value;
            }

            /**
             * Gets the value of the passengerOrCrewCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassengerOrCrewCode() {
                return passengerOrCrewCode;
            }

            /**
             * Sets the value of the passengerOrCrewCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassengerOrCrewCode(String value) {
                this.passengerOrCrewCode = value;
            }

			/**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the age property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAge() {
                return age;
            }

            /**
             * Sets the value of the age property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAge(String value) {
                this.age = value;
            }

            /**
             * Gets the value of the sex property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSex() {
                return sex;
            }

            /**
             * Sets the value of the sex property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSex(String value) {
                this.sex = value;
            }

            /**
             * Gets the value of the nationality property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNationality() {
                return nationality;
            }

            /**
             * Sets the value of the nationality property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNationality(String value) {
                this.nationality = value;
            }

            /**
             * Gets the value of the portJoinVesselCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPortJoinVesselCode() {
                return portJoinVesselCode;
            }

            /**
             * Sets the value of the portJoinVesselCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPortJoinVesselCode(String value) {
                this.portJoinVesselCode = value;
            }

            /**
             * Gets the value of the dateJoinVessel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateJoinVessel() {
                return dateJoinVessel;
            }

            /**
             * Sets the value of the dateJoinVessel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateJoinVessel(String value) {
                this.dateJoinVessel = value;
            }

            /**
             * Gets the value of the classOrRating property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClassOrRating() {
                return classOrRating;
            }

            /**
             * Sets the value of the classOrRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClassOrRating(String value) {
                this.classOrRating = value;
            }

            /**
             * Gets the value of the natureOfIllness property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNatureOfIllness() {
                return natureOfIllness;
            }

            /**
             * Sets the value of the natureOfIllness property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNatureOfIllness(String value) {
                this.natureOfIllness = value;
            }

            /**
             * Gets the value of the dateOfOnsetOfSymptom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateOfOnsetOfSymptom() {
                return dateOfOnsetOfSymptom;
            }

            /**
             * Sets the value of the dateOfOnsetOfSymptom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateOfOnsetOfSymptom(String value) {
                this.dateOfOnsetOfSymptom = value;
            }

            /**
             * Gets the value of the reportedMedicalOfficer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReportedMedicalOfficer() {
                return reportedMedicalOfficer;
            }

            /**
             * Sets the value of the reportedMedicalOfficer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReportedMedicalOfficer(String value) {
                this.reportedMedicalOfficer = value;
            }

            /**
             * Gets the value of the disposalOfCase property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisposalOfCase() {
                return disposalOfCase;
            }

            /**
             * Sets the value of the disposalOfCase property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisposalOfCase(String value) {
                this.disposalOfCase = value;
            }

            /**
             * Gets the value of the medicinesOrOther property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMedicinesOrOther() {
                return medicinesOrOther;
            }

            /**
             * Sets the value of the medicinesOrOther property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMedicinesOrOther(String value) {
                this.medicinesOrOther = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DocumentYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SubmittedPortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DateSubmitted" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NameOfShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Registration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IMONumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ArrivingFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SailingTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MasterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GrossTonnage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GrossTonnageUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Tonnage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TonnageUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CertificateCarried" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IssuedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ReInspectionRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsShipVisitedWHO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="VisitedWHOPortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DateOfVisitedWHO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ListPortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DoctorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DoctorSignDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentName",
        "documentYear",
        "userCreated",
        "submittedPortCode",
        "dateSubmitted",
        "nameOfShip",
        "registration",
        "imoNumber",
        "arrivingFrom",
        "sailingTo",
        "nationality",
        "masterName",
        "grossTonnage",
        "grossTonnageUnit",
        "tonnage",
        "tonnageUnit",
        "certificateCarried",
        "issuedAt",
        "issueDate",
        "reInspectionRequired",
        "isShipVisitedWHO",
        "visitedWHOPortCode",
        "dateOfVisitedWHO",
        "listPortName",
        "doctorName",
        "doctorSignDate"
    })
    public static class DeclarationOfHealth {

        @XmlElement(name = "DocumentName", required = true)
        protected String documentName;
        @XmlElement(name = "DocumentYear", required = true)
        protected String documentYear;
        @XmlElement(name = "UserCreated", required = true)
        protected String userCreated;
        @XmlElement(name = "SubmittedPortCode", required = true)
        protected String submittedPortCode;
        @XmlElement(name = "DateSubmitted", required = true)
        protected String dateSubmitted;
        @XmlElement(name = "NameOfShip", required = true)
        protected String nameOfShip;
        @XmlElement(name = "Registration", required = true)
        protected String registration;
        @XmlElement(name = "IMONumber", required = true)
        protected String imoNumber;
        @XmlElement(name = "ArrivingFrom", required = true)
        protected String arrivingFrom;
        @XmlElement(name = "SailingTo", required = true)
        protected String sailingTo;
        @XmlElement(name = "Nationality", required = true)
        protected String nationality;
        @XmlElement(name = "MasterName", required = true)
        protected String masterName;
        @XmlElement(name = "GrossTonnage", required = true)
        protected String grossTonnage;
        @XmlElement(name = "GrossTonnageUnit", required = true)
        protected String grossTonnageUnit;
        @XmlElement(name = "Tonnage", required = true)
        protected String tonnage;
        @XmlElement(name = "TonnageUnit", required = true)
        protected String tonnageUnit;
        @XmlElement(name = "CertificateCarried", required = true)
        protected String certificateCarried;
        @XmlElement(name = "IssuedAt", required = true)
        protected String issuedAt;
        @XmlElement(name = "IssueDate", required = true)
        protected String issueDate;
        @XmlElement(name = "ReInspectionRequired", required = true)
        protected String reInspectionRequired;
        @XmlElement(name = "IsShipVisitedWHO", required = true)
        protected String isShipVisitedWHO;
        @XmlElement(name = "VisitedWHOPortCode", required = true)
        protected String visitedWHOPortCode;
        @XmlElement(name = "DateOfVisitedWHO", required = true)
        protected String dateOfVisitedWHO;
        @XmlElement(name = "ListPortName", required = true)
        protected String listPortName;
        @XmlElement(name = "DoctorName", required = true)
        protected String doctorName;
        @XmlElement(name = "DoctorSignDate", required = true)
        protected String doctorSignDate;

        /**
         * Gets the value of the documentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentName() {
            return documentName;
        }

        /**
         * Sets the value of the documentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentName(String value) {
            this.documentName = value;
        }

        /**
         * Gets the value of the documentYear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentYear() {
            return documentYear;
        }

        /**
         * Sets the value of the documentYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentYear(String value) {
            this.documentYear = value;
        }

        /**
         * Gets the value of the userCreated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserCreated() {
            return userCreated;
        }

        /**
         * Sets the value of the userCreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserCreated(String value) {
            this.userCreated = value;
        }

        /**
         * Gets the value of the submittedPortCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmittedPortCode() {
            return submittedPortCode;
        }

        /**
         * Sets the value of the submittedPortCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmittedPortCode(String value) {
            this.submittedPortCode = value;
        }

        /**
         * Gets the value of the dateSubmitted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateSubmitted() {
            return dateSubmitted;
        }

        /**
         * Sets the value of the dateSubmitted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateSubmitted(String value) {
            this.dateSubmitted = value;
        }

        /**
         * Gets the value of the nameOfShip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameOfShip() {
            return nameOfShip;
        }

        /**
         * Sets the value of the nameOfShip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameOfShip(String value) {
            this.nameOfShip = value;
        }

        /**
         * Gets the value of the registration property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistration() {
            return registration;
        }

        /**
         * Sets the value of the registration property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistration(String value) {
            this.registration = value;
        }

        /**
         * Gets the value of the imoNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMONumber() {
            return imoNumber;
        }

        /**
         * Sets the value of the imoNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMONumber(String value) {
            this.imoNumber = value;
        }

        /**
         * Gets the value of the arrivingFrom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrivingFrom() {
            return arrivingFrom;
        }

        /**
         * Sets the value of the arrivingFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrivingFrom(String value) {
            this.arrivingFrom = value;
        }

        /**
         * Gets the value of the sailingTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSailingTo() {
            return sailingTo;
        }

        /**
         * Sets the value of the sailingTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSailingTo(String value) {
            this.sailingTo = value;
        }

        /**
         * Gets the value of the nationality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNationality() {
            return nationality;
        }

        /**
         * Sets the value of the nationality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNationality(String value) {
            this.nationality = value;
        }

        /**
         * Gets the value of the masterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMasterName() {
            return masterName;
        }

        /**
         * Sets the value of the masterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMasterName(String value) {
            this.masterName = value;
        }

        /**
         * Gets the value of the grossTonnage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrossTonnage() {
            return grossTonnage;
        }

        /**
         * Sets the value of the grossTonnage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrossTonnage(String value) {
            this.grossTonnage = value;
        }

        /**
         * Gets the value of the grossTonnageUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrossTonnageUnit() {
            return grossTonnageUnit;
        }

        /**
         * Sets the value of the grossTonnageUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrossTonnageUnit(String value) {
            this.grossTonnageUnit = value;
        }

        /**
         * Gets the value of the tonnage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTonnage() {
            return tonnage;
        }

        /**
         * Sets the value of the tonnage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTonnage(String value) {
            this.tonnage = value;
        }

        /**
         * Gets the value of the tonnageUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTonnageUnit() {
            return tonnageUnit;
        }

        /**
         * Sets the value of the tonnageUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTonnageUnit(String value) {
            this.tonnageUnit = value;
        }

        /**
         * Gets the value of the certificateCarried property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificateCarried() {
            return certificateCarried;
        }

        /**
         * Sets the value of the certificateCarried property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificateCarried(String value) {
            this.certificateCarried = value;
        }

        /**
         * Gets the value of the issuedAt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssuedAt() {
            return issuedAt;
        }

        /**
         * Sets the value of the issuedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssuedAt(String value) {
            this.issuedAt = value;
        }

        /**
         * Gets the value of the issueDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssueDate() {
            return issueDate;
        }

        /**
         * Sets the value of the issueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssueDate(String value) {
            this.issueDate = value;
        }

        /**
         * Gets the value of the reInspectionRequired property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReInspectionRequired() {
            return reInspectionRequired;
        }

        /**
         * Sets the value of the reInspectionRequired property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReInspectionRequired(String value) {
            this.reInspectionRequired = value;
        }

        /**
         * Gets the value of the isShipVisitedWHO property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsShipVisitedWHO() {
            return isShipVisitedWHO;
        }

        /**
         * Sets the value of the isShipVisitedWHO property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsShipVisitedWHO(String value) {
            this.isShipVisitedWHO = value;
        }

        /**
         * Gets the value of the visitedWHOPortCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisitedWHOPortCode() {
            return visitedWHOPortCode;
        }

        /**
         * Sets the value of the visitedWHOPortCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisitedWHOPortCode(String value) {
            this.visitedWHOPortCode = value;
        }

        /**
         * Gets the value of the dateOfVisitedWHO property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateOfVisitedWHO() {
            return dateOfVisitedWHO;
        }

        /**
         * Sets the value of the dateOfVisitedWHO property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateOfVisitedWHO(String value) {
            this.dateOfVisitedWHO = value;
        }

        /**
         * Gets the value of the listPortName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getListPortName() {
            return listPortName;
        }

        /**
         * Sets the value of the listPortName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setListPortName(String value) {
            this.listPortName = value;
        }

        /**
         * Gets the value of the doctorName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDoctorName() {
            return doctorName;
        }

        /**
         * Sets the value of the doctorName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDoctorName(String value) {
            this.doctorName = value;
        }

        /**
         * Gets the value of the doctorSignDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDoctorSignDate() {
            return doctorSignDate;
        }

        /**
         * Sets the value of the doctorSignDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDoctorSignDate(String value) {
            this.doctorSignDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HealthCrewPassenger" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="HealthCrewPassengerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PassengerOrCrewCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PassengerOrCrewName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ClassOrRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="StateVisitedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PortVisitedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ToDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "healthCrewPassenger"
    })
    public static class HealthCrewPassengerList {

        @XmlElement(name = "HealthCrewPassenger", required = true)
        protected List<HealthQuanrantineDeclare.HealthCrewPassengerList.HealthCrewPassenger> healthCrewPassenger;

        /**
         * Gets the value of the healthCrewPassenger property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the healthCrewPassenger property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHealthCrewPassenger().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HealthQuanrantineDeclare.HealthCrewPassengerList.HealthCrewPassenger }
         * 
         * 
         */
        public List<HealthQuanrantineDeclare.HealthCrewPassengerList.HealthCrewPassenger> getHealthCrewPassenger() {
            if (healthCrewPassenger == null) {
                healthCrewPassenger = new ArrayList<HealthQuanrantineDeclare.HealthCrewPassengerList.HealthCrewPassenger>();
            }
            return this.healthCrewPassenger;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="HealthCrewPassengerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PassengerOrCrewCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PassengerOrCrewName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ClassOrRating" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="StateVisitedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PortVisitedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ToDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "healthCrewPassengerCode",
            "passengerOrCrewCode",
            "passengerOrCrewName",
            "classOrRating",
            "stateVisitedCode",
            "portVisitedCode",
            "fromDate",
            "toDate"
        })
        public static class HealthCrewPassenger {

            @XmlElement(name = "HealthCrewPassengerCode", required = true)
            protected String healthCrewPassengerCode;
            @XmlElement(name = "PassengerOrCrewCode", required = true)
            protected String passengerOrCrewCode;
            @XmlElement(name = "PassengerOrCrewName", required = true)
            protected String passengerOrCrewName;
            @XmlElement(name = "ClassOrRating", required = true)
            protected String classOrRating;
            @XmlElement(name = "StateVisitedCode", required = true)
            protected String stateVisitedCode;
            @XmlElement(name = "PortVisitedCode", required = true)
            protected String portVisitedCode;
            @XmlElement(name = "FromDate", required = true)
            protected String fromDate;
            @XmlElement(name = "ToDate", required = true)
            protected String toDate;

            /**
             * Gets the value of the healthCrewPassengerCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHealthCrewPassengerCode() {
                return healthCrewPassengerCode;
            }

            /**
             * Sets the value of the healthCrewPassengerCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHealthCrewPassengerCode(String value) {
                this.healthCrewPassengerCode = value;
            }

            /**
             * Gets the value of the passengerOrCrewCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassengerOrCrewCode() {
                return passengerOrCrewCode;
            }

            /**
             * Sets the value of the passengerOrCrewCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassengerOrCrewCode(String value) {
                this.passengerOrCrewCode = value;
            }
            /**
             * Gets the value of the passengerOrCrewName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassengerOrCrewName() {
				return passengerOrCrewName;
			}
            /**
             * Sets the value of the passengerOrCrewName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
			public void setPassengerOrCrewName(String passengerOrCrewName) {
				this.passengerOrCrewName = passengerOrCrewName;
			}

			/**
             * Gets the value of the classOrRating property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClassOrRating() {
                return classOrRating;
            }

            /**
             * Sets the value of the classOrRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClassOrRating(String value) {
                this.classOrRating = value;
            }

            /**
             * Gets the value of the stateVisitedCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStateVisitedCode() {
                return stateVisitedCode;
            }

            /**
             * Sets the value of the stateVisitedCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStateVisitedCode(String value) {
                this.stateVisitedCode = value;
            }

            /**
             * Gets the value of the portVisitedCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPortVisitedCode() {
                return portVisitedCode;
            }

            /**
             * Sets the value of the portVisitedCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPortVisitedCode(String value) {
                this.portVisitedCode = value;
            }

            /**
             * Gets the value of the fromDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFromDate() {
                return fromDate;
            }

            /**
             * Sets the value of the fromDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFromDate(String value) {
                this.fromDate = value;
            }

            /**
             * Gets the value of the toDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getToDate() {
                return toDate;
            }

            /**
             * Sets the value of the toDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setToDate(String value) {
                this.toDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HealthQuestionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PersonDied" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PersonDiedNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PersonDiedReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsInfectious" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InfectiousReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IllPassengersGreaterNomal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IllPassengersNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IllPersonsOnBoard" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IllPersonsReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MedicalPractitionerConsulted" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MedicalTreatmentOrAdvice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InfectionOrSpreadOfDisease" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InfectionsReport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsSanitary" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SanitaryDes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsStowaways" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JoinShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IsAnimal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "healthQuestionCode",
        "personDied",
        "personDiedNo",
        "personDiedReport",
        "isInfectious",
        "infectiousReport",
        "illPassengersGreaterNomal",
        "illPassengersNo",
        "illPersonsOnBoard",
        "illPersonsReport",
        "medicalPractitionerConsulted",
        "medicalTreatmentOrAdvice",
        "infectionOrSpreadOfDisease",
        "infectionsReport",
        "isSanitary",
        "sanitaryDes",
        "isStowaways",
        "joinShip",
        "isAnimal"
    })
    public static class HealthQuestion {

        @XmlElement(name = "HealthQuestionCode", required = true)
        protected String healthQuestionCode;
        @XmlElement(name = "PersonDied", required = true)
        protected String personDied;
        @XmlElement(name = "PersonDiedNo", required = true)
        protected String personDiedNo;
        @XmlElement(name = "PersonDiedReport", required = true)
        protected String personDiedReport;
        @XmlElement(name = "IsInfectious", required = true)
        protected String isInfectious;
        @XmlElement(name = "InfectiousReport", required = true)
        protected String infectiousReport;
        @XmlElement(name = "IllPassengersGreaterNomal", required = true)
        protected String illPassengersGreaterNomal;
        @XmlElement(name = "IllPassengersNo", required = true)
        protected String illPassengersNo;
        @XmlElement(name = "IllPersonsOnBoard", required = true)
        protected String illPersonsOnBoard;
        @XmlElement(name = "IllPersonsReport", required = true)
        protected String illPersonsReport;
        @XmlElement(name = "MedicalPractitionerConsulted", required = true)
        protected String medicalPractitionerConsulted;
        @XmlElement(name = "MedicalTreatmentOrAdvice", required = true)
        protected String medicalTreatmentOrAdvice;
        @XmlElement(name = "InfectionOrSpreadOfDisease", required = true)
        protected String infectionOrSpreadOfDisease;
        @XmlElement(name = "InfectionsReport", required = true)
        protected String infectionsReport;
        @XmlElement(name = "IsSanitary", required = true)
        protected String isSanitary;
        @XmlElement(name = "SanitaryDes", required = true)
        protected String sanitaryDes;
        @XmlElement(name = "IsStowaways", required = true)
        protected String isStowaways;
        @XmlElement(name = "JoinShip", required = true)
        protected String joinShip;
        @XmlElement(name = "IsAnimal", required = true)
        protected String isAnimal;

        /**
         * Gets the value of the healthQuestionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHealthQuestionCode() {
            return healthQuestionCode;
        }

        /**
         * Sets the value of the healthQuestionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHealthQuestionCode(String value) {
            this.healthQuestionCode = value;
        }

        /**
         * Gets the value of the personDied property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonDied() {
            return personDied;
        }

        /**
         * Sets the value of the personDied property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonDied(String value) {
            this.personDied = value;
        }

        /**
         * Gets the value of the personDiedNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonDiedNo() {
            return personDiedNo;
        }

        /**
         * Sets the value of the personDiedNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonDiedNo(String value) {
            this.personDiedNo = value;
        }

        /**
         * Gets the value of the personDiedReport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonDiedReport() {
            return personDiedReport;
        }

        /**
         * Sets the value of the personDiedReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonDiedReport(String value) {
            this.personDiedReport = value;
        }

        /**
         * Gets the value of the isInfectious property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsInfectious() {
            return isInfectious;
        }

        /**
         * Sets the value of the isInfectious property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsInfectious(String value) {
            this.isInfectious = value;
        }

        /**
         * Gets the value of the infectiousReport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInfectiousReport() {
            return infectiousReport;
        }

        /**
         * Sets the value of the infectiousReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInfectiousReport(String value) {
            this.infectiousReport = value;
        }

        /**
         * Gets the value of the illPassengersGreaterNomal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIllPassengersGreaterNomal() {
            return illPassengersGreaterNomal;
        }

        /**
         * Sets the value of the illPassengersGreaterNomal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIllPassengersGreaterNomal(String value) {
            this.illPassengersGreaterNomal = value;
        }

        /**
         * Gets the value of the illPassengersNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIllPassengersNo() {
            return illPassengersNo;
        }

        /**
         * Sets the value of the illPassengersNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIllPassengersNo(String value) {
            this.illPassengersNo = value;
        }

        /**
         * Gets the value of the illPersonsOnBoard property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIllPersonsOnBoard() {
            return illPersonsOnBoard;
        }

        /**
         * Sets the value of the illPersonsOnBoard property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIllPersonsOnBoard(String value) {
            this.illPersonsOnBoard = value;
        }

        /**
         * Gets the value of the illPersonsReport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIllPersonsReport() {
            return illPersonsReport;
        }

        /**
         * Sets the value of the illPersonsReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIllPersonsReport(String value) {
            this.illPersonsReport = value;
        }

        /**
         * Gets the value of the medicalPractitionerConsulted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMedicalPractitionerConsulted() {
            return medicalPractitionerConsulted;
        }

        /**
         * Sets the value of the medicalPractitionerConsulted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMedicalPractitionerConsulted(String value) {
            this.medicalPractitionerConsulted = value;
        }

        /**
         * Gets the value of the medicalTreatmentOrAdvice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMedicalTreatmentOrAdvice() {
            return medicalTreatmentOrAdvice;
        }

        /**
         * Sets the value of the medicalTreatmentOrAdvice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMedicalTreatmentOrAdvice(String value) {
            this.medicalTreatmentOrAdvice = value;
        }

        /**
         * Gets the value of the infectionOrSpreadOfDisease property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInfectionOrSpreadOfDisease() {
            return infectionOrSpreadOfDisease;
        }

        /**
         * Sets the value of the infectionOrSpreadOfDisease property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInfectionOrSpreadOfDisease(String value) {
            this.infectionOrSpreadOfDisease = value;
        }

        /**
         * Gets the value of the infectionsReport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInfectionsReport() {
            return infectionsReport;
        }

        /**
         * Sets the value of the infectionsReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInfectionsReport(String value) {
            this.infectionsReport = value;
        }

        /**
         * Gets the value of the isSanitary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsSanitary() {
            return isSanitary;
        }

        /**
         * Sets the value of the isSanitary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsSanitary(String value) {
            this.isSanitary = value;
        }

        /**
         * Gets the value of the sanitaryDes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSanitaryDes() {
            return sanitaryDes;
        }

        /**
         * Sets the value of the sanitaryDes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSanitaryDes(String value) {
            this.sanitaryDes = value;
        }

        /**
         * Gets the value of the isStowaways property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsStowaways() {
            return isStowaways;
        }

        /**
         * Sets the value of the isStowaways property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsStowaways(String value) {
            this.isStowaways = value;
        }

        /**
         * Gets the value of the joinShip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJoinShip() {
            return joinShip;
        }

        /**
         * Sets the value of the joinShip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJoinShip(String value) {
            this.joinShip = value;
        }

        /**
         * Gets the value of the isAnimal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsAnimal() {
            return isAnimal;
        }

        /**
         * Sets the value of the isAnimal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsAnimal(String value) {
            this.isAnimal = value;
        }

    }

}
