//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 04:43:22 AM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PortRegion" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PortRegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PortRegionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ReferencePortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "portRegion"
})
@XmlRootElement(name = "PortRegionList")
public class PortRegionList {

    @XmlElement(name = "PortRegion", required = true)
    protected List<PortRegionList.PortRegion> portRegion;

    /**
     * Gets the value of the portRegion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portRegion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortRegionList.PortRegion }
     * 
     * 
     */
    public List<PortRegionList.PortRegion> getPortRegion() {
        if (portRegion == null) {
            portRegion = new ArrayList<PortRegionList.PortRegion>();
        }
        return this.portRegion;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PortRegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PortRegionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ReferencePortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "portRegionCode",
        "portRegionName",
        "referencePortCode",
        "status"
    })
    public static class PortRegion {

        @XmlElement(name = "PortRegionCode", required = true)
        protected String portRegionCode;
        @XmlElement(name = "PortRegionName", required = true)
        protected String portRegionName;
        @XmlElement(name = "ReferencePortCode", required = true)
        protected String referencePortCode;
        @XmlElement(name = "Status", required = true)
        protected String status;

        /**
         * Gets the value of the portRegionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPortRegionCode() {
            return portRegionCode;
        }

        /**
         * Sets the value of the portRegionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPortRegionCode(String value) {
            this.portRegionCode = value;
        }

        /**
         * Gets the value of the portRegionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPortRegionName() {
            return portRegionName;
        }

        /**
         * Sets the value of the portRegionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPortRegionName(String value) {
            this.portRegionName = value;
        }

        /**
         * Gets the value of the referencePortCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferencePortCode() {
            return referencePortCode;
        }

        /**
         * Sets the value of the referencePortCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferencePortCode(String value) {
            this.referencePortCode = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }

}
