//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 05:23:19 AM ICT 
//


package vn.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserCreated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isArrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CallSign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PortOfArrivalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateOfArrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PortHarbourCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PortRegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PortWharfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastPortOfCallCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxCodeOfShipownersAgents" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfShipownersAgents" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipAgencyAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipAgencyPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipAgencyFax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipAgencyEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GrossTonnage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GrossTonnageUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetTonnage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CargoOnBoard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VolumeCargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CargoUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetTonnageUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PositionOfShipInPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BriefParticularsOfVoyage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BriefDescriptionOfTheCargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MasterSigned" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaritimePortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NextProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CargoDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RatedPower" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SeatingCapacity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LyingCapacity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastMaritimePortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastPortRegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastPortHarbourCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastPortWharfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NextMaritimePortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NextPortRegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NextPortHarbourCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NextPortWharfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CargoList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentName",
    "documentYear",
    "userCreated",
    "isArrival",
    "nameOfShip",
    "shipTypeCode",
    "callSign",
    "portOfArrivalCode",
    "dateOfArrival",
    "portHarbourCode",
    "portRegionCode",
    "portWharfCode",
    "nameOfMaster",
    "lastPortOfCallCode",
    "taxCodeOfShipownersAgents",
    "nameOfShipownersAgents",
    "shipAgencyAddress",
    "shipAgencyPhone",
    "shipAgencyFax",
    "shipAgencyEmail",
    "grossTonnage",
    "grossTonnageUnit",
    "netTonnage",
    "cargoOnBoard",
    "cargo",
    "volumeCargo",
    "cargoUnit",
    "netTonnageUnit",
    "positionOfShipInPort",
    "briefParticularsOfVoyage",
    "briefDescriptionOfTheCargo",
    "remarks",
    "signPlace",
    "signDate",
    "masterSigned",
    "maritimePortCode",
    "lastProvinceCode",
    "nextProvinceCode",
    "cargoDescription",
    "ratedPower",
    "seatingCapacity",
    "lyingCapacity",
    "lastMaritimePortCode",
    "lastPortRegionCode",
    "lastPortHarbourCode",
    "lastPortWharfCode",
    "nextMaritimePortCode",
    "nextPortRegionCode",
    "nextPortHarbourCode",
    "nextPortWharfCode",
    "cargoList"
})
@XmlRootElement(name = "PTTNDGeneralDeclaration")
public class PTTNDGeneralDeclaration {

    @XmlElement(name = "DocumentName", required = true)
    protected String documentName;
    @XmlElement(name = "DocumentYear", required = true)
    protected String documentYear;
    @XmlElement(name = "UserCreated", required = true)
    protected String userCreated;
    @XmlElement(required = true)
    protected String isArrival;
    @XmlElement(name = "NameOfShip", required = true)
    protected String nameOfShip;
    @XmlElement(name = "ShipTypeCode", required = true)
    protected String shipTypeCode;
    @XmlElement(name = "CallSign", required = true)
    protected String callSign;
    @XmlElement(name = "PortOfArrivalCode", required = true)
    protected String portOfArrivalCode;
    @XmlElement(name = "DateOfArrival", required = true)
    protected String dateOfArrival;
    @XmlElement(name = "PortHarbourCode", required = true)
    protected String portHarbourCode;
    @XmlElement(name = "PortRegionCode", required = true)
    protected String portRegionCode;
    @XmlElement(name = "PortWharfCode", required = true)
    protected String portWharfCode;
    @XmlElement(name = "NameOfMaster", required = true)
    protected String nameOfMaster;
    @XmlElement(name = "LastPortOfCallCode", required = true)
    protected String lastPortOfCallCode;
    @XmlElement(name = "TaxCodeOfShipownersAgents", required = true)
    protected String taxCodeOfShipownersAgents;
    @XmlElement(name = "NameOfShipownersAgents", required = true)
    protected String nameOfShipownersAgents;
    @XmlElement(name = "ShipAgencyAddress", required = true)
    protected String shipAgencyAddress;
    @XmlElement(name = "ShipAgencyPhone", required = true)
    protected String shipAgencyPhone;
    @XmlElement(name = "ShipAgencyFax", required = true)
    protected String shipAgencyFax;
    @XmlElement(name = "ShipAgencyEmail", required = true)
    protected String shipAgencyEmail;
    @XmlElement(name = "GrossTonnage", required = true)
    protected String grossTonnage;
    @XmlElement(name = "GrossTonnageUnit", required = true)
    protected String grossTonnageUnit;
    @XmlElement(name = "NetTonnage", required = true)
    protected String netTonnage;
    @XmlElement(name = "CargoOnBoard", required = true)
    protected String cargoOnBoard;
    @XmlElement(name = "Cargo", required = true)
    protected String cargo;
    @XmlElement(name = "VolumeCargo", required = true)
    protected String volumeCargo;
    @XmlElement(name = "CargoUnit", required = true)
    protected String cargoUnit;
    @XmlElement(name = "NetTonnageUnit", required = true)
    protected String netTonnageUnit;
    @XmlElement(name = "PositionOfShipInPort", required = true)
    protected String positionOfShipInPort;
    @XmlElement(name = "BriefParticularsOfVoyage", required = true)
    protected String briefParticularsOfVoyage;
    @XmlElement(name = "BriefDescriptionOfTheCargo", required = true)
    protected String briefDescriptionOfTheCargo;
    @XmlElement(name = "Remarks", required = true)
    protected String remarks;
    @XmlElement(name = "SignPlace", required = true)
    protected String signPlace;
    @XmlElement(name = "SignDate", required = true)
    protected String signDate;
    @XmlElement(name = "MasterSigned", required = true)
    protected String masterSigned;
    @XmlElement(name = "MaritimePortCode", required = true)
    protected String maritimePortCode;
    @XmlElement(name = "LastProvinceCode", required = true)
    protected String lastProvinceCode;
    @XmlElement(name = "NextProvinceCode", required = true)
    protected String nextProvinceCode;
    @XmlElement(name = "CargoDescription", required = true)
    protected String cargoDescription;
    @XmlElement(name = "RatedPower", required = true)
    protected String ratedPower;
    @XmlElement(name = "SeatingCapacity", required = true)
    protected String seatingCapacity;
    @XmlElement(name = "LyingCapacity", required = true)
    protected String lyingCapacity;
    @XmlElement(name = "LastMaritimePortCode", required = true)
    protected String lastMaritimePortCode;
    @XmlElement(name = "LastPortRegionCode", required = true)
    protected String lastPortRegionCode;
    @XmlElement(name = "LastPortHarbourCode", required = true)
    protected String lastPortHarbourCode;
    @XmlElement(name = "LastPortWharfCode", required = true)
    protected String lastPortWharfCode;
    @XmlElement(name = "NextMaritimePortCode", required = true)
    protected String nextMaritimePortCode;
    @XmlElement(name = "NextPortRegionCode", required = true)
    protected String nextPortRegionCode;
    @XmlElement(name = "NextPortHarbourCode", required = true)
    protected String nextPortHarbourCode;
    @XmlElement(name = "NextPortWharfCode", required = true)
    protected String nextPortWharfCode;
    @XmlElement(name = "CargoList", required = true)
    protected List<PTTNDGeneralDeclaration.CargoList> cargoList;

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentYear() {
        return documentYear;
    }

    /**
     * Sets the value of the documentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentYear(String value) {
        this.documentYear = value;
    }

    /**
     * Gets the value of the userCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * Sets the value of the userCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCreated(String value) {
        this.userCreated = value;
    }

    /**
     * Gets the value of the isArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsArrival() {
        return isArrival;
    }

    /**
     * Sets the value of the isArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsArrival(String value) {
        this.isArrival = value;
    }

    /**
     * Gets the value of the nameOfShip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfShip() {
        return nameOfShip;
    }

    /**
     * Sets the value of the nameOfShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfShip(String value) {
        this.nameOfShip = value;
    }

    /**
     * Gets the value of the shipTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipTypeCode() {
        return shipTypeCode;
    }

    /**
     * Sets the value of the shipTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipTypeCode(String value) {
        this.shipTypeCode = value;
    }

    /**
     * Gets the value of the callSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSign() {
        return callSign;
    }

    /**
     * Sets the value of the callSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSign(String value) {
        this.callSign = value;
    }

    /**
     * Gets the value of the portOfArrivalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortOfArrivalCode() {
        return portOfArrivalCode;
    }

    /**
     * Sets the value of the portOfArrivalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortOfArrivalCode(String value) {
        this.portOfArrivalCode = value;
    }

    /**
     * Gets the value of the dateOfArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfArrival() {
        return dateOfArrival;
    }

    /**
     * Sets the value of the dateOfArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfArrival(String value) {
        this.dateOfArrival = value;
    }

    /**
     * Gets the value of the portHarbourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortHarbourCode() {
        return portHarbourCode;
    }

    /**
     * Sets the value of the portHarbourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortHarbourCode(String value) {
        this.portHarbourCode = value;
    }

    /**
     * Gets the value of the portRegionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortRegionCode() {
        return portRegionCode;
    }

    /**
     * Sets the value of the portRegionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortRegionCode(String value) {
        this.portRegionCode = value;
    }

    /**
     * Gets the value of the portWharfCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortWharfCode() {
        return portWharfCode;
    }

    /**
     * Sets the value of the portWharfCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortWharfCode(String value) {
        this.portWharfCode = value;
    }

    /**
     * Gets the value of the nameOfMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfMaster() {
        return nameOfMaster;
    }

    /**
     * Sets the value of the nameOfMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfMaster(String value) {
        this.nameOfMaster = value;
    }

    /**
     * Gets the value of the lastPortOfCallCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPortOfCallCode() {
        return lastPortOfCallCode;
    }

    /**
     * Sets the value of the lastPortOfCallCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPortOfCallCode(String value) {
        this.lastPortOfCallCode = value;
    }

    /**
     * Gets the value of the taxCodeOfShipownersAgents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCodeOfShipownersAgents() {
        return taxCodeOfShipownersAgents;
    }

    /**
     * Sets the value of the taxCodeOfShipownersAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCodeOfShipownersAgents(String value) {
        this.taxCodeOfShipownersAgents = value;
    }

    /**
     * Gets the value of the nameOfShipownersAgents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfShipownersAgents() {
        return nameOfShipownersAgents;
    }

    /**
     * Sets the value of the nameOfShipownersAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfShipownersAgents(String value) {
        this.nameOfShipownersAgents = value;
    }

    /**
     * Gets the value of the shipAgencyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipAgencyAddress() {
        return shipAgencyAddress;
    }

    /**
     * Sets the value of the shipAgencyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipAgencyAddress(String value) {
        this.shipAgencyAddress = value;
    }

    /**
     * Gets the value of the shipAgencyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipAgencyPhone() {
        return shipAgencyPhone;
    }

    /**
     * Sets the value of the shipAgencyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipAgencyPhone(String value) {
        this.shipAgencyPhone = value;
    }

    /**
     * Gets the value of the shipAgencyFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipAgencyFax() {
        return shipAgencyFax;
    }

    /**
     * Sets the value of the shipAgencyFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipAgencyFax(String value) {
        this.shipAgencyFax = value;
    }

    /**
     * Gets the value of the shipAgencyEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipAgencyEmail() {
        return shipAgencyEmail;
    }

    /**
     * Sets the value of the shipAgencyEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipAgencyEmail(String value) {
        this.shipAgencyEmail = value;
    }

    /**
     * Gets the value of the grossTonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrossTonnage() {
        return grossTonnage;
    }

    /**
     * Sets the value of the grossTonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrossTonnage(String value) {
        this.grossTonnage = value;
    }

    /**
     * Gets the value of the grossTonnageUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrossTonnageUnit() {
        return grossTonnageUnit;
    }

    /**
     * Sets the value of the grossTonnageUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrossTonnageUnit(String value) {
        this.grossTonnageUnit = value;
    }

    /**
     * Gets the value of the netTonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetTonnage() {
        return netTonnage;
    }

    /**
     * Sets the value of the netTonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetTonnage(String value) {
        this.netTonnage = value;
    }

    /**
     * Gets the value of the cargoOnBoard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoOnBoard() {
        return cargoOnBoard;
    }

    /**
     * Sets the value of the cargoOnBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoOnBoard(String value) {
        this.cargoOnBoard = value;
    }

    /**
     * Gets the value of the cargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargo() {
        return cargo;
    }

    /**
     * Sets the value of the cargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargo(String value) {
        this.cargo = value;
    }

    /**
     * Gets the value of the volumeCargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeCargo() {
        return volumeCargo;
    }

    /**
     * Sets the value of the volumeCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeCargo(String value) {
        this.volumeCargo = value;
    }

    /**
     * Gets the value of the cargoUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoUnit() {
        return cargoUnit;
    }

    /**
     * Sets the value of the cargoUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoUnit(String value) {
        this.cargoUnit = value;
    }

    /**
     * Gets the value of the netTonnageUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetTonnageUnit() {
        return netTonnageUnit;
    }

    /**
     * Sets the value of the netTonnageUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetTonnageUnit(String value) {
        this.netTonnageUnit = value;
    }

    /**
     * Gets the value of the positionOfShipInPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionOfShipInPort() {
        return positionOfShipInPort;
    }

    /**
     * Sets the value of the positionOfShipInPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionOfShipInPort(String value) {
        this.positionOfShipInPort = value;
    }

    /**
     * Gets the value of the briefParticularsOfVoyage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBriefParticularsOfVoyage() {
        return briefParticularsOfVoyage;
    }

    /**
     * Sets the value of the briefParticularsOfVoyage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBriefParticularsOfVoyage(String value) {
        this.briefParticularsOfVoyage = value;
    }

    /**
     * Gets the value of the briefDescriptionOfTheCargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBriefDescriptionOfTheCargo() {
        return briefDescriptionOfTheCargo;
    }

    /**
     * Sets the value of the briefDescriptionOfTheCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBriefDescriptionOfTheCargo(String value) {
        this.briefDescriptionOfTheCargo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the signPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignPlace() {
        return signPlace;
    }

    /**
     * Sets the value of the signPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignPlace(String value) {
        this.signPlace = value;
    }

    /**
     * Gets the value of the signDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * Sets the value of the signDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignDate(String value) {
        this.signDate = value;
    }

    /**
     * Gets the value of the masterSigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterSigned() {
        return masterSigned;
    }

    /**
     * Sets the value of the masterSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterSigned(String value) {
        this.masterSigned = value;
    }

    /**
     * Gets the value of the maritimePortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritimePortCode() {
        return maritimePortCode;
    }

    /**
     * Sets the value of the maritimePortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritimePortCode(String value) {
        this.maritimePortCode = value;
    }

    /**
     * Gets the value of the lastProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastProvinceCode() {
        return lastProvinceCode;
    }

    /**
     * Sets the value of the lastProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastProvinceCode(String value) {
        this.lastProvinceCode = value;
    }

    /**
     * Gets the value of the nextProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextProvinceCode() {
        return nextProvinceCode;
    }

    /**
     * Sets the value of the nextProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextProvinceCode(String value) {
        this.nextProvinceCode = value;
    }

    /**
     * Gets the value of the cargoDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoDescription() {
        return cargoDescription;
    }

    /**
     * Sets the value of the cargoDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoDescription(String value) {
        this.cargoDescription = value;
    }

    /**
     * Gets the value of the ratedPower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatedPower() {
        return ratedPower;
    }

    /**
     * Sets the value of the ratedPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatedPower(String value) {
        this.ratedPower = value;
    }

    /**
     * Gets the value of the seatingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatingCapacity() {
        return seatingCapacity;
    }

    /**
     * Sets the value of the seatingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatingCapacity(String value) {
        this.seatingCapacity = value;
    }

    /**
     * Gets the value of the lyingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLyingCapacity() {
        return lyingCapacity;
    }

    /**
     * Sets the value of the lyingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLyingCapacity(String value) {
        this.lyingCapacity = value;
    }

    /**
     * Gets the value of the lastMaritimePortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastMaritimePortCode() {
        return lastMaritimePortCode;
    }

    /**
     * Sets the value of the lastMaritimePortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastMaritimePortCode(String value) {
        this.lastMaritimePortCode = value;
    }

    /**
     * Gets the value of the lastPortRegionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPortRegionCode() {
        return lastPortRegionCode;
    }

    /**
     * Sets the value of the lastPortRegionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPortRegionCode(String value) {
        this.lastPortRegionCode = value;
    }

    /**
     * Gets the value of the lastPortHarbourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPortHarbourCode() {
        return lastPortHarbourCode;
    }

    /**
     * Sets the value of the lastPortHarbourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPortHarbourCode(String value) {
        this.lastPortHarbourCode = value;
    }

    /**
     * Gets the value of the lastPortWharfCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPortWharfCode() {
        return lastPortWharfCode;
    }

    /**
     * Sets the value of the lastPortWharfCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPortWharfCode(String value) {
        this.lastPortWharfCode = value;
    }

    /**
     * Gets the value of the nextMaritimePortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextMaritimePortCode() {
        return nextMaritimePortCode;
    }

    /**
     * Sets the value of the nextMaritimePortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextMaritimePortCode(String value) {
        this.nextMaritimePortCode = value;
    }

    /**
     * Gets the value of the nextPortRegionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextPortRegionCode() {
        return nextPortRegionCode;
    }

    /**
     * Sets the value of the nextPortRegionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextPortRegionCode(String value) {
        this.nextPortRegionCode = value;
    }

    /**
     * Gets the value of the nextPortHarbourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextPortHarbourCode() {
        return nextPortHarbourCode;
    }

    /**
     * Sets the value of the nextPortHarbourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextPortHarbourCode(String value) {
        this.nextPortHarbourCode = value;
    }

    /**
     * Gets the value of the nextPortWharfCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextPortWharfCode() {
        return nextPortWharfCode;
    }

    /**
     * Sets the value of the nextPortWharfCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextPortWharfCode(String value) {
        this.nextPortWharfCode = value;
    }

    /**
     * Gets the value of the cargoList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cargoList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCargoList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PTTNDGeneralDeclaration.CargoList }
     * 
     * 
     */
    public List<PTTNDGeneralDeclaration.CargoList> getCargoList() {
        if (cargoList == null) {
            cargoList = new ArrayList<PTTNDGeneralDeclaration.CargoList>();
        }
        return this.cargoList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category",
        "type",
        "name",
        "description",
        "quantity",
        "unit"
    })
    public static class CargoList {

        @XmlElement(name = "Category", required = true)
        protected String category;
        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Quantity", required = true)
        protected String quantity;
        @XmlElement(name = "Unit", required = true)
        protected String unit;

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuantity(String value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnit() {
            return unit;
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnit(String value) {
            this.unit = value;
        }

    }

}
