//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 03:04:12 PM ICT 
//


package vn.nsw.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItineraryNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PortofAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NoticeShipType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TestingFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TestingTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlagStateOfShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMONumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CallSign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VRCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegistryNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipCaptain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AnchoringPortHarbourCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AnchoringPortWharfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShiftingPortHarbourCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShiftingPortWharfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DirectorOfMaritime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CertificateNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VersionNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsApproval" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApprovalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApprovalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsCancel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CancelDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CancelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CancelNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Representative" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DigitalAttachedFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttachedFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StampStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShownDraftxF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitShownDraftxF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShownDraftxA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitShownDraftxA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LOA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LOAUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DWT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DWTUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TugBoat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="From_" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="To_" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChanelCodeList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChanelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itineraryNo",
    "portofAuthority",
    "documentName",
    "documentYear",
    "noticeShipType",
    "testingFrom",
    "testingTo",
    "nameOfShip",
    "flagStateOfShip",
    "imoNumber",
    "callSign",
    "vrCode",
    "registryNumber",
    "shipCaptain",
    "anchoringPortHarbourCode",
    "anchoringPortWharfCode",
    "shiftingPortHarbourCode",
    "shiftingPortWharfCode",
    "issueDate",
    "directorOfMaritime",
    "certificateNo",
    "requestState",
    "versionNo",
    "isApproval",
    "approvalDate",
    "approvalName",
    "remarks",
    "isCancel",
    "cancelDate",
    "cancelName",
    "cancelNote",
    "representative",
    "digitalAttachedFile",
    "signName",
    "signTitle",
    "signDate",
    "signPlace",
    "attachedFile",
    "stampStatus",
    "shownDraftxF",
    "unitShownDraftxF",
    "shownDraftxA",
    "unitShownDraftxA",
    "loa",
    "loaunit",
    "dwt",
    "dwtunit",
    "tugBoat",
    "from",
    "to",
    "chanelCodeList",
    "chanelName",
    "modifiedDate"
})
@XmlRootElement(name = "VmaScheduleTesting")
public class VmaScheduleTesting {

    @XmlElement(name = "ItineraryNo", required = true)
    protected String itineraryNo;
    @XmlElement(name = "PortofAuthority", required = true)
    protected String portofAuthority;
    @XmlElement(name = "DocumentName", required = true)
    protected String documentName;
    @XmlElement(name = "DocumentYear", required = true)
    protected String documentYear;
    @XmlElement(name = "NoticeShipType", required = true)
    protected String noticeShipType;
    @XmlElement(name = "TestingFrom", required = true)
    protected String testingFrom;
    @XmlElement(name = "TestingTo", required = true)
    protected String testingTo;
    @XmlElement(name = "NameOfShip", required = true)
    protected String nameOfShip;
    @XmlElement(name = "FlagStateOfShip", required = true)
    protected String flagStateOfShip;
    @XmlElement(name = "IMONumber", required = true)
    protected String imoNumber;
    @XmlElement(name = "CallSign", required = true)
    protected String callSign;
    @XmlElement(name = "VRCode", required = true)
    protected String vrCode;
    @XmlElement(name = "RegistryNumber", required = true)
    protected String registryNumber;
    @XmlElement(name = "ShipCaptain", required = true)
    protected String shipCaptain;
    @XmlElement(name = "AnchoringPortHarbourCode", required = true)
    protected String anchoringPortHarbourCode;
    @XmlElement(name = "AnchoringPortWharfCode", required = true)
    protected String anchoringPortWharfCode;
    @XmlElement(name = "ShiftingPortHarbourCode", required = true)
    protected String shiftingPortHarbourCode;
    @XmlElement(name = "ShiftingPortWharfCode", required = true)
    protected String shiftingPortWharfCode;
    @XmlElement(name = "IssueDate", required = true)
    protected String issueDate;
    @XmlElement(name = "DirectorOfMaritime", required = true)
    protected String directorOfMaritime;
    @XmlElement(name = "CertificateNo", required = true)
    protected String certificateNo;
    @XmlElement(name = "RequestState", required = true)
    protected String requestState;
    @XmlElement(name = "VersionNo", required = true)
    protected String versionNo;
    @XmlElement(name = "IsApproval", required = true)
    protected String isApproval;
    @XmlElement(name = "ApprovalDate", required = true)
    protected String approvalDate;
    @XmlElement(name = "ApprovalName", required = true)
    protected String approvalName;
    @XmlElement(name = "Remarks", required = true)
    protected String remarks;
    @XmlElement(name = "IsCancel", required = true)
    protected String isCancel;
    @XmlElement(name = "CancelDate", required = true)
    protected String cancelDate;
    @XmlElement(name = "CancelName", required = true)
    protected String cancelName;
    @XmlElement(name = "CancelNote", required = true)
    protected String cancelNote;
    @XmlElement(name = "Representative", required = true)
    protected String representative;
    @XmlElement(name = "DigitalAttachedFile", required = true)
    protected String digitalAttachedFile;
    @XmlElement(name = "SignName", required = true)
    protected String signName;
    @XmlElement(name = "SignTitle", required = true)
    protected String signTitle;
    @XmlElement(name = "SignDate", required = true)
    protected String signDate;
    @XmlElement(name = "SignPlace", required = true)
    protected String signPlace;
    @XmlElement(name = "AttachedFile", required = true)
    protected String attachedFile;
    @XmlElement(name = "StampStatus", required = true)
    protected String stampStatus;
    @XmlElement(name = "ShownDraftxF", required = true)
    protected String shownDraftxF;
    @XmlElement(name = "UnitShownDraftxF", required = true)
    protected String unitShownDraftxF;
    @XmlElement(name = "ShownDraftxA", required = true)
    protected String shownDraftxA;
    @XmlElement(name = "UnitShownDraftxA", required = true)
    protected String unitShownDraftxA;
    @XmlElement(name = "LOA", required = true)
    protected String loa;
    @XmlElement(name = "LOAUNIT", required = true)
    protected String loaunit;
    @XmlElement(name = "DWT", required = true)
    protected String dwt;
    @XmlElement(name = "DWTUNIT", required = true)
    protected String dwtunit;
    @XmlElement(name = "TugBoat", required = true)
    protected String tugBoat;
    @XmlElement(name = "From_", required = true)
    protected String from;
    @XmlElement(name = "To_", required = true)
    protected String to;
    @XmlElement(name = "ChanelCodeList", required = true)
    protected String chanelCodeList;
    @XmlElement(name = "ChanelName", required = true)
    protected String chanelName;
    @XmlElement(name = "ModifiedDate", required = true)
    protected String modifiedDate;

    /**
     * Gets the value of the itineraryNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItineraryNo() {
        return itineraryNo;
    }

    /**
     * Sets the value of the itineraryNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItineraryNo(String value) {
        this.itineraryNo = value;
    }

    /**
     * Gets the value of the portofAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortofAuthority() {
        return portofAuthority;
    }

    /**
     * Sets the value of the portofAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortofAuthority(String value) {
        this.portofAuthority = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentYear() {
        return documentYear;
    }

    /**
     * Sets the value of the documentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentYear(String value) {
        this.documentYear = value;
    }

    /**
     * Gets the value of the noticeShipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoticeShipType() {
        return noticeShipType;
    }

    /**
     * Sets the value of the noticeShipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoticeShipType(String value) {
        this.noticeShipType = value;
    }

    /**
     * Gets the value of the testingFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestingFrom() {
        return testingFrom;
    }

    /**
     * Sets the value of the testingFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestingFrom(String value) {
        this.testingFrom = value;
    }

    /**
     * Gets the value of the testingTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestingTo() {
        return testingTo;
    }

    /**
     * Sets the value of the testingTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestingTo(String value) {
        this.testingTo = value;
    }

    /**
     * Gets the value of the nameOfShip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfShip() {
        return nameOfShip;
    }

    /**
     * Sets the value of the nameOfShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfShip(String value) {
        this.nameOfShip = value;
    }

    /**
     * Gets the value of the flagStateOfShip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagStateOfShip() {
        return flagStateOfShip;
    }

    /**
     * Sets the value of the flagStateOfShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagStateOfShip(String value) {
        this.flagStateOfShip = value;
    }

    /**
     * Gets the value of the imoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMONumber() {
        return imoNumber;
    }

    /**
     * Sets the value of the imoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMONumber(String value) {
        this.imoNumber = value;
    }

    /**
     * Gets the value of the callSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSign() {
        return callSign;
    }

    /**
     * Sets the value of the callSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSign(String value) {
        this.callSign = value;
    }

    /**
     * Gets the value of the vrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVRCode() {
        return vrCode;
    }

    /**
     * Sets the value of the vrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVRCode(String value) {
        this.vrCode = value;
    }

    /**
     * Gets the value of the registryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistryNumber() {
        return registryNumber;
    }

    /**
     * Sets the value of the registryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistryNumber(String value) {
        this.registryNumber = value;
    }

    /**
     * Gets the value of the shipCaptain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipCaptain() {
        return shipCaptain;
    }

    /**
     * Sets the value of the shipCaptain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipCaptain(String value) {
        this.shipCaptain = value;
    }

    /**
     * Gets the value of the anchoringPortHarbourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnchoringPortHarbourCode() {
        return anchoringPortHarbourCode;
    }

    /**
     * Sets the value of the anchoringPortHarbourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnchoringPortHarbourCode(String value) {
        this.anchoringPortHarbourCode = value;
    }

    /**
     * Gets the value of the anchoringPortWharfCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnchoringPortWharfCode() {
        return anchoringPortWharfCode;
    }

    /**
     * Sets the value of the anchoringPortWharfCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnchoringPortWharfCode(String value) {
        this.anchoringPortWharfCode = value;
    }

    /**
     * Gets the value of the shiftingPortHarbourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShiftingPortHarbourCode() {
        return shiftingPortHarbourCode;
    }

    /**
     * Sets the value of the shiftingPortHarbourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShiftingPortHarbourCode(String value) {
        this.shiftingPortHarbourCode = value;
    }

    /**
     * Gets the value of the shiftingPortWharfCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShiftingPortWharfCode() {
        return shiftingPortWharfCode;
    }

    /**
     * Sets the value of the shiftingPortWharfCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShiftingPortWharfCode(String value) {
        this.shiftingPortWharfCode = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the directorOfMaritime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorOfMaritime() {
        return directorOfMaritime;
    }

    /**
     * Sets the value of the directorOfMaritime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorOfMaritime(String value) {
        this.directorOfMaritime = value;
    }

    /**
     * Gets the value of the certificateNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * Sets the value of the certificateNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateNo(String value) {
        this.certificateNo = value;
    }

    /**
     * Gets the value of the requestState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestState() {
        return requestState;
    }

    /**
     * Sets the value of the requestState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestState(String value) {
        this.requestState = value;
    }

    /**
     * Gets the value of the versionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * Sets the value of the versionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionNo(String value) {
        this.versionNo = value;
    }

    /**
     * Gets the value of the isApproval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsApproval() {
        return isApproval;
    }

    /**
     * Sets the value of the isApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsApproval(String value) {
        this.isApproval = value;
    }

    /**
     * Gets the value of the approvalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalDate() {
        return approvalDate;
    }

    /**
     * Sets the value of the approvalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalDate(String value) {
        this.approvalDate = value;
    }

    /**
     * Gets the value of the approvalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalName() {
        return approvalName;
    }

    /**
     * Sets the value of the approvalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalName(String value) {
        this.approvalName = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the isCancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCancel() {
        return isCancel;
    }

    /**
     * Sets the value of the isCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCancel(String value) {
        this.isCancel = value;
    }

    /**
     * Gets the value of the cancelDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * Sets the value of the cancelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelDate(String value) {
        this.cancelDate = value;
    }

    /**
     * Gets the value of the cancelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelName() {
        return cancelName;
    }

    /**
     * Sets the value of the cancelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelName(String value) {
        this.cancelName = value;
    }

    /**
     * Gets the value of the cancelNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelNote() {
        return cancelNote;
    }

    /**
     * Sets the value of the cancelNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelNote(String value) {
        this.cancelNote = value;
    }

    /**
     * Gets the value of the representative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * Sets the value of the representative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentative(String value) {
        this.representative = value;
    }

    /**
     * Gets the value of the digitalAttachedFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitalAttachedFile() {
        return digitalAttachedFile;
    }

    /**
     * Sets the value of the digitalAttachedFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitalAttachedFile(String value) {
        this.digitalAttachedFile = value;
    }

    /**
     * Gets the value of the signName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignName() {
        return signName;
    }

    /**
     * Sets the value of the signName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignName(String value) {
        this.signName = value;
    }

    /**
     * Gets the value of the signTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignTitle() {
        return signTitle;
    }

    /**
     * Sets the value of the signTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignTitle(String value) {
        this.signTitle = value;
    }

    /**
     * Gets the value of the signDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * Sets the value of the signDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignDate(String value) {
        this.signDate = value;
    }

    /**
     * Gets the value of the signPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignPlace() {
        return signPlace;
    }

    /**
     * Sets the value of the signPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignPlace(String value) {
        this.signPlace = value;
    }

    /**
     * Gets the value of the attachedFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedFile() {
        return attachedFile;
    }

    /**
     * Sets the value of the attachedFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedFile(String value) {
        this.attachedFile = value;
    }

    /**
     * Gets the value of the stampStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStampStatus() {
        return stampStatus;
    }

    /**
     * Sets the value of the stampStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStampStatus(String value) {
        this.stampStatus = value;
    }

    /**
     * Gets the value of the shownDraftxF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShownDraftxF() {
        return shownDraftxF;
    }

    /**
     * Sets the value of the shownDraftxF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShownDraftxF(String value) {
        this.shownDraftxF = value;
    }

    /**
     * Gets the value of the unitShownDraftxF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitShownDraftxF() {
        return unitShownDraftxF;
    }

    /**
     * Sets the value of the unitShownDraftxF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitShownDraftxF(String value) {
        this.unitShownDraftxF = value;
    }

    /**
     * Gets the value of the shownDraftxA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShownDraftxA() {
        return shownDraftxA;
    }

    /**
     * Sets the value of the shownDraftxA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShownDraftxA(String value) {
        this.shownDraftxA = value;
    }

    /**
     * Gets the value of the unitShownDraftxA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitShownDraftxA() {
        return unitShownDraftxA;
    }

    /**
     * Sets the value of the unitShownDraftxA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitShownDraftxA(String value) {
        this.unitShownDraftxA = value;
    }

    /**
     * Gets the value of the loa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOA() {
        return loa;
    }

    /**
     * Sets the value of the loa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOA(String value) {
        this.loa = value;
    }

    /**
     * Gets the value of the loaunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOAUNIT() {
        return loaunit;
    }

    /**
     * Sets the value of the loaunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOAUNIT(String value) {
        this.loaunit = value;
    }

    /**
     * Gets the value of the dwt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDWT() {
        return dwt;
    }

    /**
     * Sets the value of the dwt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDWT(String value) {
        this.dwt = value;
    }

    /**
     * Gets the value of the dwtunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDWTUNIT() {
        return dwtunit;
    }

    /**
     * Sets the value of the dwtunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDWTUNIT(String value) {
        this.dwtunit = value;
    }

    /**
     * Gets the value of the tugBoat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTugBoat() {
        return tugBoat;
    }

    /**
     * Sets the value of the tugBoat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTugBoat(String value) {
        this.tugBoat = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the chanelCodeList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChanelCodeList() {
        return chanelCodeList;
    }

    /**
     * Sets the value of the chanelCodeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChanelCodeList(String value) {
        this.chanelCodeList = value;
    }

    /**
     * Gets the value of the chanelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChanelName() {
        return chanelName;
    }

    /**
     * Sets the value of the chanelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChanelName(String value) {
        this.chanelName = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

}
