//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 03:04:12 PM ICT 
//


package vn.nsw.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItineraryNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PortofAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfShip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NoticeShipType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityOfficeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityOfficialNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Evacuated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvacuateOfficialCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvacuateCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvacuateOfficialNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvacuateDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvacuateReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itineraryNo",
    "portofAuthority",
    "nameOfShip",
    "documentName",
    "documentYear",
    "noticeShipType",
    "securityOfficeCode",
    "securityCompanyName",
    "securityOfficialNo",
    "securityDate",
    "securityPlace",
    "securityReason",
    "evacuated",
    "evacuateOfficialCode",
    "evacuateCompanyName",
    "evacuateOfficialNo",
    "evacuateDate",
    "evacuateReason",
    "modifiedDate"
})
@XmlRootElement(name = "VmaScheduleSecurity")
public class VmaScheduleSecurity {

    @XmlElement(name = "ItineraryNo", required = true)
    protected String itineraryNo;
    @XmlElement(name = "PortofAuthority", required = true)
    protected String portofAuthority;
    @XmlElement(name = "NameOfShip", required = true)
    protected String nameOfShip;
    @XmlElement(name = "DocumentName", required = true)
    protected String documentName;
    @XmlElement(name = "DocumentYear", required = true)
    protected String documentYear;
    @XmlElement(name = "NoticeShipType", required = true)
    protected String noticeShipType;
    @XmlElement(name = "SecurityOfficeCode", required = true)
    protected String securityOfficeCode;
    @XmlElement(name = "SecurityCompanyName", required = true)
    protected String securityCompanyName;
    @XmlElement(name = "SecurityOfficialNo", required = true)
    protected String securityOfficialNo;
    @XmlElement(name = "SecurityDate", required = true)
    protected String securityDate;
    @XmlElement(name = "SecurityPlace", required = true)
    protected String securityPlace;
    @XmlElement(name = "SecurityReason", required = true)
    protected String securityReason;
    @XmlElement(name = "Evacuated", required = true)
    protected String evacuated;
    @XmlElement(name = "EvacuateOfficialCode", required = true)
    protected String evacuateOfficialCode;
    @XmlElement(name = "EvacuateCompanyName", required = true)
    protected String evacuateCompanyName;
    @XmlElement(name = "EvacuateOfficialNo", required = true)
    protected String evacuateOfficialNo;
    @XmlElement(name = "EvacuateDate", required = true)
    protected String evacuateDate;
    @XmlElement(name = "EvacuateReason", required = true)
    protected String evacuateReason;
    @XmlElement(name = "ModifiedDate", required = true)
    protected String modifiedDate;

    /**
     * Gets the value of the itineraryNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItineraryNo() {
        return itineraryNo;
    }

    /**
     * Sets the value of the itineraryNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItineraryNo(String value) {
        this.itineraryNo = value;
    }

    /**
     * Gets the value of the portofAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortofAuthority() {
        return portofAuthority;
    }

    /**
     * Sets the value of the portofAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortofAuthority(String value) {
        this.portofAuthority = value;
    }

    /**
     * Gets the value of the nameOfShip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfShip() {
        return nameOfShip;
    }

    /**
     * Sets the value of the nameOfShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfShip(String value) {
        this.nameOfShip = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentYear() {
        return documentYear;
    }

    /**
     * Sets the value of the documentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentYear(String value) {
        this.documentYear = value;
    }

    /**
     * Gets the value of the noticeShipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoticeShipType() {
        return noticeShipType;
    }

    /**
     * Sets the value of the noticeShipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoticeShipType(String value) {
        this.noticeShipType = value;
    }

    /**
     * Gets the value of the securityOfficeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityOfficeCode() {
        return securityOfficeCode;
    }

    /**
     * Sets the value of the securityOfficeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityOfficeCode(String value) {
        this.securityOfficeCode = value;
    }

    /**
     * Gets the value of the securityCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityCompanyName() {
        return securityCompanyName;
    }

    /**
     * Sets the value of the securityCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityCompanyName(String value) {
        this.securityCompanyName = value;
    }

    /**
     * Gets the value of the securityOfficialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityOfficialNo() {
        return securityOfficialNo;
    }

    /**
     * Sets the value of the securityOfficialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityOfficialNo(String value) {
        this.securityOfficialNo = value;
    }

    /**
     * Gets the value of the securityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityDate() {
        return securityDate;
    }

    /**
     * Sets the value of the securityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityDate(String value) {
        this.securityDate = value;
    }

    /**
     * Gets the value of the securityPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPlace() {
        return securityPlace;
    }

    /**
     * Sets the value of the securityPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPlace(String value) {
        this.securityPlace = value;
    }

    /**
     * Gets the value of the securityReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityReason() {
        return securityReason;
    }

    /**
     * Sets the value of the securityReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityReason(String value) {
        this.securityReason = value;
    }

    /**
     * Gets the value of the evacuated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvacuated() {
        return evacuated;
    }

    /**
     * Sets the value of the evacuated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvacuated(String value) {
        this.evacuated = value;
    }

    /**
     * Gets the value of the evacuateOfficialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvacuateOfficialCode() {
        return evacuateOfficialCode;
    }

    /**
     * Sets the value of the evacuateOfficialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvacuateOfficialCode(String value) {
        this.evacuateOfficialCode = value;
    }

    /**
     * Gets the value of the evacuateCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvacuateCompanyName() {
        return evacuateCompanyName;
    }

    /**
     * Sets the value of the evacuateCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvacuateCompanyName(String value) {
        this.evacuateCompanyName = value;
    }

    /**
     * Gets the value of the evacuateOfficialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvacuateOfficialNo() {
        return evacuateOfficialNo;
    }

    /**
     * Sets the value of the evacuateOfficialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvacuateOfficialNo(String value) {
        this.evacuateOfficialNo = value;
    }

    /**
     * Gets the value of the evacuateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvacuateDate() {
        return evacuateDate;
    }

    /**
     * Sets the value of the evacuateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvacuateDate(String value) {
        this.evacuateDate = value;
    }

    /**
     * Gets the value of the evacuateReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvacuateReason() {
        return evacuateReason;
    }

    /**
     * Sets the value of the evacuateReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvacuateReason(String value) {
        this.evacuateReason = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

}
