//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.05 at 03:53:30 PM ICT 
//


package vn.nsw.fac;

import javax.xml.bind.annotation.XmlRegistry;

import vn.nsw.model.DmHistoryPilotList;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class DmHistoryPilotListFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public DmHistoryPilotListFactory() {
    }

    /**
     * Create an instance of {@link DmHistoryPilotList }
     * 
     */
    public DmHistoryPilotList createDmHistoryPilotList() {
        return new DmHistoryPilotList();
    }

    /**
     * Create an instance of {@link DmHistoryPilotList.DmHistoryPilot }
     * 
     */
    public DmHistoryPilotList.DmHistoryPilot createDmHistoryPilotListDmHistoryPilot() {
        return new DmHistoryPilotList.DmHistoryPilot();
    }

}
