//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.08 at 05:31:12 PM ICT 
//


package vn.nsw.fac;

import javax.xml.bind.annotation.XmlRegistry;

import vn.nsw.model.Invoices;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class InvoicesFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn
     * 
     */
    public InvoicesFactory() {
    }

    /**
     * Create an instance of {@link Invoices }
     * 
     */
    public Invoices createInvoices() {
        return new Invoices();
    }

    /**
     * Create an instance of {@link Invoices.Inv }
     * 
     */
    public Invoices.Inv createInvoicesInv() {
        return new Invoices.Inv();
    }

    /**
     * Create an instance of {@link Invoices.Inv.Invoice }
     * 
     */
    public Invoices.Inv.Invoice createInvoicesInvInvoice() {
        return new Invoices.Inv.Invoice();
    }

    /**
     * Create an instance of {@link Invoices.Inv.Invoice.Products }
     * 
     */
    public Invoices.Inv.Invoice.Products createInvoicesInvInvoiceProducts() {
        return new Invoices.Inv.Invoice.Products();
    }

    /**
     * Create an instance of {@link Invoices.Inv.Invoice.Products.Product }
     * 
     */
    public Invoices.Inv.Invoice.Products.Product createInvoicesInvInvoiceProductsProduct() {
        return new Invoices.Inv.Invoice.Products.Product();
    }

}
