//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 03:11:43 PM ICT 
//


package vn.nsw.fac;

import javax.xml.bind.annotation.XmlRegistry;

import vn.nsw.model.inland.PTTNDPassengerList;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn.nsw.model.inland package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class PTTNDPassengerListFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn.nsw.model.inland
     * 
     */
    public PTTNDPassengerListFactory() {
    }

    /**
     * Create an instance of {@link PTTNDPassengerList.ListPassengers }
     * 
     */
    public PTTNDPassengerList.ListPassengers createPTTNDPassengerListListPassengers() {
        return new PTTNDPassengerList.ListPassengers();
    }

    /**
     * Create an instance of {@link PTTNDPassengerList }
     * 
     */
    public PTTNDPassengerList createPTTNDPassengerList() {
        return new PTTNDPassengerList();
    }

    /**
     * Create an instance of {@link PTTNDPassengerList.ListPassengers.Passenger }
     * 
     */
    public PTTNDPassengerList.ListPassengers.Passenger createPTTNDPassengerListListPassengersPassenger() {
        return new PTTNDPassengerList.ListPassengers.Passenger();
    }

}
