//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 05:27:50 PM ICT 
//


package vn.nsw.fac.inland;

import javax.xml.bind.annotation.XmlRegistry;

import vn.nsw.model.inland.InlandAdditionalRequirements;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class InlandAdditionalRequirementsFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public InlandAdditionalRequirementsFactory() {
    }

    /**
     * Create an instance of {@link InlandAdditionalRequirements }
     * 
     */
    public InlandAdditionalRequirements createInlandAdditionalRequirements() {
        return new InlandAdditionalRequirements();
    }

}
